# Outputs for the Terraform configuration
# Some of these outputs are needed to configure the Quarkus application.
# In addition, we output some of the generated resource names (generated by the `aztfmod/azurecaf` provider).

# AKS outputs

output "aks-resource-group" {
  value       = azurerm_resource_group.aks-rg.name
  description = "Name of the Resource Group for the AKS cluster"
}

output "aks-cluster-name" {
  value       = azurerm_kubernetes_cluster.aks.name
  description = "Name of the AKS cluster"
}

output "service-account-name" {
  value       = azurerm_user_assigned_identity.aks-msi.name
  description = "Name of the Workload Identity for our Quarkus demo application"
}

output "service-account-client-id" {
  value       = azurerm_user_assigned_identity.aks-msi.client_id
  description = "client-id of the Workload Identity for our Quarkus demo application"
}

output "application-namespace" {
  value       = var.application_namespace
  description = "Namespace for the Quarkus application in AKS"
}

# Container Registry outputs

output "container-registry-resource-group" {
  value       = azurerm_resource_group.acr-rg.name
  description = "Name of the Resource Group for the Azure Container Registry"
}

output "container-registry" {
  value       = "${azurerm_container_registry.acr.name}.azurecr.io"
  description = "Name of the Azure Container Registry for storing container images"
}

# Service Bus outputs

output "servicebus-resource-group" {
  value       = azurerm_resource_group.servicebus-rg.name
  description = "Name of the Resource Group for the Service Bus"
}

output "servicebus-namespace" {
  value       = azurerm_servicebus_namespace.sb-ns.name
  description = "Name of the Service Bus namespace"
}

output "servicebus-fqdn" {
  value       = "${azurerm_servicebus_namespace.sb-ns.name}.servicebus.windows.net"
  description = "Fully qualified domain name of the Service Bus namespace host"
}

output "servicebus-topic" {
  value       = azurerm_servicebus_topic.sb-topic.name
  description = "Name of the Service Bus topic"
}

output "servicebus-subscription" {
  value       = azurerm_servicebus_subscription.topic-subscription.name
  description = "Name of the Service Bus subscription"
}

output "servicebus-connection-string" {
  value       = nonsensitive(azurerm_servicebus_topic_authorization_rule.topic-listen.primary_connection_string)
  description = "Connection string for accessing the Service Bus topic via SAS authentication"
}
