# Outputs for the Terraform configuration
# Some of these outputs are needed to configure the Quarkus application.
# In addition, we output some of the generated resource names (generated by the `aztfmod/azurecaf` provider).

# AKS outputs

output "aks-cluster-name" {
  value       = azurerm_kubernetes_cluster.aks.name
  description = "Name of the AKS cluster"
}

output "service-account-name" {
  value       = azurerm_user_assigned_identity.aks-msi.name
  description = "Name of the Workload Identity for our Quarkus demo application"
}

output "service-account-client-id" {
  value       = azurerm_user_assigned_identity.aks-msi.client_id
  description = "Client-id of the Workload Identity for our Quarkus demo application"
}

output "service-account-tenant-id" {
  value       = azurerm_user_assigned_identity.aks-msi.tenant_id
  description = "Tenant-id used for this infra project"
}

output "application-namespace" {
  value       = var.application_namespace
  description = "Namespace for the Quarkus application in AKS"
}

# Container Registry outputs

output "container-registry" {
  value       = "${azurerm_container_registry.acr.name}.azurecr.io"
  description = "Name of the Azure Container Registry for storing container images"
}

# Service Bus outputs

output "servicebus-namespace" {
  value       = azurerm_servicebus_namespace.sb-ns.name
  description = "Name of the Service Bus namespace"
}

output "servicebus-topic" {
  value       = azurerm_servicebus_topic.sb-topic.name
  description = "Name of the Service Bus topic"
}

output "servicebus-subscription" {
  value       = azurerm_servicebus_subscription.topic-subscription.name
  description = "Name of the Service Bus subscription"
}

output "servicebus-connection-string" {
  value       = nonsensitive(azurerm_servicebus_topic_authorization_rule.topic-listen.primary_connection_string)
  description = "Connection string for accessing the Service Bus topic via SAS authentication"
}

# Postgres outputs

output "postgres-fqdn" {
  value       = azurerm_postgresql_flexible_server.postgres.fqdn
  description = "Fully qualified domain name of the Azure Database for PostgreSQL flexible servers"
}

output "postgres-jdbc-url" {
  value       = "jdbc:postgresql://${azurerm_postgresql_flexible_server.postgres.fqdn}/demo?authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin&sslmode=require"
  description = "JDBC url of the database"
}

output "postgres-jdbc-url-no-plugin" {
  value       = "jdbc:postgresql://${azurerm_postgresql_flexible_server.postgres.fqdn}/demo?sslmode=require"
  description = "JDBC url of the database"
}
