# Customization of the Helm chart.
# Create a copy of this file as "values.yaml" in the same directory and add the missing values
# based on the terraform output.

image:
  # The image repository to use (full image name without tag),
  # '<container-registry from the terraform output>/azure-quarkus-native-demo/servicebus-workload-id'
  repository:
  pullPolicy: Always
  tag: latest

# connection to Azure Service Bus topic subscription
servicebus:
  # The connection string to the Service Bus topic subscription,
  # 'servicebus-connection-string' from the terraform output.
  connectionString=
  # The name of the topic to use,
  # 'servicebus-topic' from the terraform output.
  topic=topic
  # The name of the subscription to use,
  # 'servicebus-subscription' from the terraform output.
  subscription=subscription
